#!/usr/bin/python
# extend_handin.py
#
# Utility script for reopening handin directory for specific students, if
# extensions are to be given for whatever reason. Once the extension time has
# passed, the close_handin script can be used to again close all handins.
#
# Edric Kusuma <ekusuma@cmu.edu>

import optparse;
import os;
import subprocess;
from env import *;

isVerbose = False;

# Returns a tuple of (options, args) parsed from the command line.
def getArgs():
    usage = "usage: %prog [-v] hwNum studentID0, studentID1, ...";
    parser = optparse.OptionParser(usage=usage)
    parser.add_option("-v", action="store_true", dest="isVerbose",
                      default=False, help="verbose script output");
    (options, args) = parser.parse_args();
    if (len(args) < 1):
        parser.error("Must specify homework number as first arg");
    if (len(args) < 2):
        parser.error("Must specify at least one student ID");
    return (options, args);

# Sets AFS permissions such that the student may write to the directory
# Admins have usual admin permissions, and other students may not access
def setStudentPerms(studentID, path):
    fsCmd = ["fs", "seta", "-dir", path, "-clear", "-acl"];
    peoplePerms = [
        "system:web-srv-users", "rl",
        "ee240:ta", "all",
        "ee240:staff", "all",
        "ee240", "all",
        "system:administrators", "all",
        studentID, "write"
    ];
    fsCmd += peoplePerms;
    subprocess.call(fsCmd);

def openStudentDirs(basePath, ids):
    for student in ids:
        path = basePath + "/" + student.lower();
        setStudentPerms(student, path);

def main():
    (options, args) = getArgs();
    hwNum = args[0];
    studentList = args[1:];
    global isVerbose;
    isVerbose = options.isVerbose;

    handinDir = HANDIN_DIR + "/" + hwNum;

    openStudentDirs(handinDir, studentList);

    names = "";
    for student in studentList:
        names += student + " ";
    print("Extensions granted for " + names);
    return 0;

exit(main());
