#!/bin/sh
# init_handin240.sh
#
# Utility script that every student needs to run to be able to use the handin
# script. Workaround is necessary because we cannot install the reportlab module
# for all users on the machines. This script only ever needs to be run once.
#
# Usage:
#   - Just run the executable ./init_handin

pip3 install --user reportlab
pip3 install --user pygments # Required for syntax highlighting
