#!/usr/bin/python
# open_handin.py
#
# Utility script to create student directories in the assignment's handin
# folder. Requires a student roster file (filename and path detailed in env.py)
# that has all student Andrew IDs, separated by a newline. Requires the user
# running the script to be someone with access to the STAFF folder.

import optparse;
import os;
import subprocess;
from env import *;

isVerbose = False;

# Returns a tuple of (options, args) parsed from the command line.
def getArgs():
    usage = "usage: %prog [-rv] hwNum";
    parser = optparse.OptionParser(usage=usage)
    parser.add_option("-r", action="store", type="string", dest="rosterPath",
                      default=ROSTER, help="path to student roster file");
    parser.add_option("-v", action="store_true", dest="isVerbose",
                      default=False, help="verbose script output");
    (options, args) = parser.parse_args();
    if (len(args) != 1):
        parser.error("Must specify homework number as arg");
    return (options, args);

# Sets AFS permissions such that the student may write to the directory
# Admins have usual admin permissions, and other students may not access
def setStudentPerms(studentID, path):
    fsCmd = ["fs", "seta", "-dir", path, "-clear", "-acl"];
    peoplePerms = [
        "system:web-srv-users", "rl",
        "ee240:ta", "all",
        "ee240:staff", "all",
        "ee240", "all",
        "system:administrators", "all",
        studentID, "write"
    ];
    fsCmd += peoplePerms;
    subprocess.call(fsCmd);

# Creates a directory for each student inside of the basePath directory. ids
# must be an array of student IDs.
def createStudentDirs(basePath, ids):
    for student in ids:
        path = basePath + "/" + student.lower();
        if (not os.path.exists(path)):
            os.mkdir(basePath + "/" + student.lower());
        elif (isVerbose):
            print("Handin dir already exists for " + student.lower() +
                    ", skipping");
        setStudentPerms(student, path);

def main():
    (options, args) = getArgs();
    hwNum = args[0];
    global isVerbose;
    isVerbose = options.isVerbose;

    handinDir = HANDIN_DIR + "/" + hwNum;
    print("Creating handin directories for " + hwNum + " in " + handinDir);
    if (not os.path.exists(handinDir)):
        os.mkdir(handinDir);
    elif (isVerbose):
        print("Path exists for " + handinDir + ", skipping");

    if (isVerbose):
        print("Using roster file in " + options.rosterPath + "\n");
    rosterFile = open(options.rosterPath, "r");
    studentIDs = rosterFile.read().split();
    createStudentDirs(handinDir, studentIDs);
    rosterFile.close();

    print("Handin directories created.");
    return 0;

exit(main());
